### ISSUE TITLE
.NET core 2

### ISSUE THREAD

**Issue by hexactauy** [apawsey/DbContextScope#3]
Are u planning a upgrade to .NET Core 2 ?

Regards.

**Comment by rinkeb** [comment]
We use https://www.nuget.org/packages/EntityFramework.DbContextScope/ without any issues (so far) on .net core 2.

**Comment by patavarini** [comment]
I´m facing some problems with IObjectContextAdapter not being in EFCore. Should i use EF on this project? i was migrating all references to Core.

thx for help.

**Comment by apawsey** [comment]
I'm going to make a point of updating the compatibility as soon as possible... obviously a bit late for this issue!
